//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Fail extends JPanel {
    private JLabel jl_icici;
    private JLabel jl_incomptran;
    private JLabel jl_refresh;
    private JLabel jl_sorry;
    private JLabel jl_error;
    private JButton jb_back;
    private JLabel jl_navi;

    public Fail() {
        //construct components
        jl_icici = new JLabel ("ICICI");
        jl_incomptran = new JLabel ("The transaction was incomplete. No credit was debited.");
        jl_refresh = new JLabel ("Please refresh your gateway page and re enter your credit card details.");
        jl_sorry = new JLabel ("Sorry for the inconvenience.");
        jl_error = new JLabel ("An ERROR occurred during the transaction and had to be aborted.");
        jb_back = new JButton ("Back");
        jl_navi = new JLabel ("Click back to navigate to the gateway page.");

        //adjust size and set layout
        setPreferredSize (new Dimension (560, 435));
        setLayout (null);

        //add components
        add (jl_icici);
        add (jl_incomptran);
        add (jl_refresh);
        add (jl_sorry);
        add (jl_error);
        add (jb_back);
        add (jl_navi);

        //set component bounds (only needed by Absolute Positioning)
        jl_icici.setBounds (0, 0, 565, 65);
        jl_incomptran.setBounds (110, 115, 335, 30);
        jl_refresh.setBounds (65, 150, 410, 30);
        jl_sorry.setBounds (65, 185, 170, 30);
        jl_error.setBounds (90, 80, 380, 30);
        jb_back.setBounds (210, 230, 100, 25);
        jl_navi.setBounds (230, 185, 250, 30);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Fail");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Fail());
        frame.pack();
        frame.setVisible (true);
    }
}
