//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Preview extends JPanel {
    private JLabel jl_prev;

    public Preview() {
        //construct components
        jl_prev = new JLabel (new ImageIcon("ipl-ticket[1].jpg"));

        //adjust size and set layout
        setPreferredSize (new Dimension (560, 435));
        setLayout (null);

        //add components
        add (jl_prev);

        //set component bounds (only needed by Absolute Positioning)
        jl_prev.setBounds (35, 45, 490, 335);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Preview");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Preview());
        frame.pack();
        frame.setVisible (true);
    }
}
