//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

class Button{
    JFrame jf_button;
	 JPanel jp_button;
    public JToggleButton jtb_1;
    public JToggleButton jtb_2;
    public JToggleButton jtb_3;
    public JToggleButton jtb_4;
    public JToggleButton jtb_5;
    public JToggleButton jtb_6;
    public JToggleButton jtb_7;
    public JToggleButton jtb_8;
    public JToggleButton jtb_9;
    public JToggleButton jtb_10;
    public JToggleButton jtb_11;
    public JToggleButton jtb_12;
    public JToggleButton jtb_13;
    public JToggleButton jtb_14;
    public JToggleButton jtb_15;
    public JToggleButton jtb_16;
    public JToggleButton jtb_17;
    public JToggleButton jtb_18;
    public JToggleButton jtb_19;
    public JToggleButton jtb_20;
    public JToggleButton jtb_21;
    public JToggleButton jtb_22;
    public JToggleButton jtb_23;
    public JToggleButton jtb_24;
    public JToggleButton jtb_25;
    public JToggleButton jtb_26;
    public JToggleButton jtb_27;
    public JToggleButton jtb_28;
    public JToggleButton jtb_29;
    public JToggleButton jtb_30;
    public JButton jb_confirm;
    public JLabel jl_pitch;
    int i = 0;
    WindowAdapter wl;
	 
	  void buildButton()
	 {
	    jf_button = new JFrame("Choose your Tickets");
		  jf_button.setDefaultCloseOperation (JFrame.DO_NOTHING_ON_CLOSE);
        jp_button = new JPanel();
		  jp_button.setBackground(new Color(135,206,250));
		  jf_button.add(jp_button);
	     buttons();
		  jf_button.pack();
        jf_button.setVisible (true);
	}
    
	 void buttons() {
        //construct components
        jtb_1 = new JToggleButton ("", false);
        jtb_2 = new JToggleButton ("", false);
        jtb_3 = new JToggleButton ("", false);
        jtb_4 = new JToggleButton ("", false);
        jtb_5 = new JToggleButton ("", false);
        jtb_6 = new JToggleButton ("", false);
        jtb_7 = new JToggleButton ("", false);
        jtb_8 = new JToggleButton ("", false);
        jtb_9 = new JToggleButton ("", false);
        jtb_10 = new JToggleButton ("", false);
        jtb_11 = new JToggleButton ("", false);
        jtb_12 = new JToggleButton ("", false);
        jtb_13 = new JToggleButton ("", false);
        jtb_14 = new JToggleButton ("", false);
        jtb_15 = new JToggleButton ("", false);
        jtb_16 = new JToggleButton ("", false);
        jtb_17 = new JToggleButton ("", false);
        jtb_18 = new JToggleButton ("", false);
        jtb_19 = new JToggleButton ("", false);
        jtb_20 = new JToggleButton ("", false);
        jtb_21 = new JToggleButton ("", false);
        jtb_22 = new JToggleButton ("", false);
        jtb_23 = new JToggleButton ("", false);
        jtb_24 = new JToggleButton ("", false);
        jtb_25 = new JToggleButton ("", false);
        jtb_26 = new JToggleButton ("", false);
        jtb_27 = new JToggleButton ("", false);
        jtb_28 = new JToggleButton ("", false);
        jtb_29 = new JToggleButton ("", false);
        jtb_30 = new JToggleButton ("", false);
        jb_confirm = new JButton ("Confirm");
        jl_pitch = new JLabel ("");

        //adjust size and set layout
        jp_button.setPreferredSize (new Dimension (560, 435));
        jp_button.setLayout (null);

        //add components
        jp_button.add (jtb_1);
        jp_button.add (jtb_2);
        jp_button.add (jtb_3);
        jp_button.add (jtb_4);
        jp_button.add (jtb_5);
        jp_button.add (jtb_6);
        jp_button.add (jtb_7);
        jp_button.add (jtb_8);
        jp_button.add (jtb_9);
        jp_button.add (jtb_10);
        jp_button.add (jtb_11);
        jp_button.add (jtb_12);
        jp_button.add (jtb_13);
        jp_button.add (jtb_14);
        jp_button.add (jtb_15);
        jp_button.add (jtb_16);
        jp_button.add (jtb_17);
        jp_button.add (jtb_18);
        jp_button.add (jtb_19);
        jp_button.add (jtb_20);
        jp_button.add (jtb_21);
        jp_button.add (jtb_22);
        jp_button.add (jtb_23);
        jp_button.add (jtb_24);
        jp_button.add (jtb_25);
        jp_button.add (jtb_26);
        jp_button.add (jtb_27);
        jp_button.add (jtb_28);
        jp_button.add (jtb_29);
        jp_button.add (jtb_30);
        jp_button.add (jb_confirm);
        jp_button.add (jl_pitch);

        //set component bounds (only needed by Absolute Positioning)
        jtb_1.setBounds (100, 65, 45, 40);
        jtb_2.setBounds (150, 65, 45, 40);
        jtb_3.setBounds (200, 65, 45, 40);
        jtb_4.setBounds (250, 65, 45, 40);
        jtb_5.setBounds (300, 65, 45, 40);
        jtb_6.setBounds (350, 65, 45, 40);
        jtb_7.setBounds (100, 110, 45, 40);
        jtb_8.setBounds (150, 110, 45, 40);
        jtb_9.setBounds (200, 110, 45, 40);
        jtb_10.setBounds (250, 110, 45, 40);
        jtb_11.setBounds (300, 110, 45, 40);
        jtb_12.setBounds (350, 110, 45, 40);
        jtb_13.setBounds (100, 155, 45, 40);
        jtb_14.setBounds (150, 155, 45, 40);
        jtb_15.setBounds (200, 155, 45, 40);
        jtb_16.setBounds (250, 155, 45, 40);
        jtb_17.setBounds (300, 155, 45, 40);
        jtb_18.setBounds (350, 155, 45, 40);
        jtb_19.setBounds (100, 200, 45, 40);
        jtb_20.setBounds (150, 200, 45, 40);
        jtb_21.setBounds (200, 200, 45, 40);
        jtb_22.setBounds (250, 200, 45, 40);
        jtb_23.setBounds (300, 200, 45, 40);
        jtb_24.setBounds (350, 200, 45, 40);
        jtb_25.setBounds (100, 245, 45, 40);
        jtb_26.setBounds (150, 245, 45, 40);
        jtb_27.setBounds (200, 245, 45, 40);
        jtb_28.setBounds (250, 245, 45, 40);
        jtb_29.setBounds (300, 245, 45, 40);
        jtb_30.setBounds (350, 245, 45, 40);
        jb_confirm.setBounds (440, 65, 95, 30);
        jl_pitch.setBounds (55, 295, 390, 125);
        
		  ActionListener al = new ActionListener()
		  {
		     public void actionPerformed(ActionEvent e)
			  {
			     if(e.getSource()==jtb_1)
				  {
				     boolean sel = jtb_1.isSelected();  
					  if(sel)
					     jtb_1.setText("B");
					  else
					     jtb_1.setText("");	  
					    
					 // jtb_1.setEnabled(false);
				  }
				  if(e.getSource()==jtb_2)
				  {
				  boolean sel = jtb_2.isSelected();  
					  if(sel)
					     jtb_2.setText("B");
					  else
					     jtb_2.setText("");
				     					    
					  
				  }
				  if(e.getSource()==jtb_3)
				  {
				     boolean sel = jtb_3.isSelected();  
					  if(sel)
					     jtb_3.setText("B");
					  else
					     jtb_3.setText("");
					    
					  
				  }
				  if(e.getSource()==jtb_4)
				  {
				    boolean sel = jtb_4.isSelected();  
					  if(sel)
					     jtb_4.setText("B");
					  else
					     jtb_4.setText("");
					    
				  }
				  if(e.getSource()==jtb_5)
				  {
                boolean sel = jtb_5.isSelected();  
					  if(sel)
					     jtb_5.setText("B");
					  else
					     jtb_5.setText("");					    
					    
				  }
				  if(e.getSource()==jtb_6)
				  {
				    boolean sel = jtb_6.isSelected();  
					  if(sel)
					     jtb_6.setText("B");
					  else
					     jtb_6.setText("");					    
					    
				  }
				  
				  if(e.getSource()==jtb_7)
				  {
				    boolean sel = jtb_7.isSelected();  
					  if(sel)
					     jtb_7.setText("B");
					  else
					     jtb_7.setText("");					    
				  }
				  if(e.getSource()==jtb_8)
				  {
				     boolean sel = jtb_8.isSelected();  
					  if(sel)
					     jtb_8.setText("B");
					  else
					     jtb_8.setText("");					    
					    
				  }
				  if(e.getSource()==jtb_9)
				  {
				     boolean sel = jtb_9.isSelected();  
					  if(sel)
					     jtb_9.setText("B");
					  else
					     jtb_9.setText("");					    
				  }
				  if(e.getSource()==jtb_10)
				  {
				    boolean sel = jtb_10.isSelected();  
					  if(sel)
					     jtb_10.setText("B");
					  else
					     jtb_10.setText("");					    
				  }
				  if(e.getSource()==jtb_11)
				  {
				     boolean sel = jtb_11.isSelected();  
					  if(sel)
					     jtb_11.setText("B");
					  else
					     jtb_11.setText("");
					    
				  }
				  if(e.getSource()==jtb_12)
				  {
				     boolean sel = jtb_12.isSelected();  
					  if(sel)
					     jtb_12.setText("B");
					  else
					     jtb_12.setText("");					    
				  }
				  if(e.getSource()==jtb_13)
				  {
				    boolean sel = jtb_13.isSelected();  
					  if(sel)
					     jtb_13.setText("B");
					  else
					     jtb_13.setText("");					    
				  }
				  if(e.getSource()==jtb_14)
				  {
				    boolean sel = jtb_14.isSelected();  
					  if(sel)
					     jtb_14.setText("B");
					  else
					     jtb_14.setText("");					    
				  }
				  if(e.getSource()==jtb_15)
				  {
				    boolean sel = jtb_15.isSelected();  
					  if(sel)
					     jtb_15.setText("B");
					  else
					     jtb_15.setText("");
					    
				  }
				  if(e.getSource()==jtb_16)
				  {
				    boolean sel = jtb_16.isSelected();  
					  if(sel)
					     jtb_16.setText("B");
					  else
					     jtb_16.setText("");
					    
				  }
				  if(e.getSource()==jtb_17)
				  {
				    boolean sel = jtb_17.isSelected();  
					  if(sel)
					     jtb_17.setText("B");
					  else
					     jtb_17.setText("");					    
				  }
				  if(e.getSource()==jtb_18)
				  {
				     boolean sel = jtb_18.isSelected();  
					  if(sel)
					     jtb_18.setText("B");
					  else
					     jtb_18.setText("");
					    
				  }
				  if(e.getSource()==jtb_19)
				  {
				    boolean sel = jtb_19.isSelected();  
					  if(sel)
					     jtb_19.setText("B");
					  else
					     jtb_19.setText("");
					    
				  }
				  if(e.getSource()==jtb_20)
				  {
				    boolean sel = jtb_20.isSelected();  
					  if(sel)
					     jtb_20.setText("B");
					  else
					     jtb_20.setText("");					    
				  }
				  if(e.getSource()==jtb_21)
				  {
				    boolean sel = jtb_21.isSelected();  
					  if(sel)
					     jtb_21.setText("B");
					  else
					     jtb_21.setText("");					    
				  }
				  if(e.getSource()==jtb_22)
				  {
				    boolean sel = jtb_22.isSelected();  
					  if(sel)
					     jtb_22.setText("B");
					  else
					     jtb_22.setText("");					    
				  }
				  if(e.getSource()==jtb_23)
				  {
				     boolean sel = jtb_23.isSelected();  
					  if(sel)
					     jtb_23.setText("B");
					  else
					     jtb_23.setText("");					    
				  }
				  
				  if(e.getSource()==jtb_24)
				  {
				    boolean sel = jtb_24.isSelected();  
					  if(sel)
					     jtb_24.setText("B");
					  else
					     jtb_24.setText("");					    
				  }
				  if(e.getSource()==jtb_25)
				  {
				    boolean sel = jtb_25.isSelected();  
					  if(sel)
					     jtb_25.setText("B");
					  else
					     jtb_25.setText("");					    
				  }
				  if(e.getSource()==jtb_26)
				  {
				    boolean sel = jtb_26.isSelected();  
					  if(sel)
					     jtb_26.setText("B");
					  else
					     jtb_26.setText("");					    
				  }
				  if(e.getSource()==jtb_27)
				  {
				    boolean sel = jtb_27.isSelected();  
					  if(sel)
					     jtb_27.setText("B");
					  else
					     jtb_27.setText("");					    
				  }
				  if(e.getSource()==jtb_28)
				  {
				    boolean sel = jtb_28.isSelected();  
					  if(sel)
					     jtb_28.setText("B");
					  else
					     jtb_28.setText("");					    
				  }
				  if(e.getSource()==jtb_29)
				  {
				    boolean sel = jtb_29.isSelected();  
					  if(sel)
					     jtb_29.setText("B");
					  else
					     jtb_29.setText("");
					    
				  }
				  if(e.getSource()==jtb_30)
				  {
				    boolean sel = jtb_30.isSelected();  
					  if(sel)
					     jtb_30.setText("B");
					  else
					     jtb_30.setText("");					    
				  }
				  
					//	jt_tic.setText(""+i);
			     }

		  };
		  jtb_1.addActionListener(al);
		  jtb_2.addActionListener(al);
		  jtb_3.addActionListener(al);
		  jtb_4.addActionListener(al);
		  jtb_5.addActionListener(al);
		  jtb_6.addActionListener(al);
		  jtb_7.addActionListener(al);
		  jtb_8.addActionListener(al);
		  jtb_9.addActionListener(al);
		  jtb_10.addActionListener(al);
		  jtb_11.addActionListener(al);
		  jtb_12.addActionListener(al);
		  jtb_13.addActionListener(al);
		  jtb_14.addActionListener(al);
		  jtb_15.addActionListener(al);
		  jtb_16.addActionListener(al);
		  jtb_17.addActionListener(al);
		  jtb_18.addActionListener(al);
		  jtb_19.addActionListener(al);
		  jtb_20.addActionListener(al);
		  jtb_21.addActionListener(al);
		  jtb_22.addActionListener(al);
		  jtb_23.addActionListener(al);
		  jtb_24.addActionListener(al);
		  jtb_25.addActionListener(al);
		  jtb_26.addActionListener(al);
		  jtb_27.addActionListener(al);
		  jtb_28.addActionListener(al);
		  jtb_29.addActionListener(al);
		  jtb_30.addActionListener(al);
	   //  jb_confirm.addActionListener(al);
		  			
		  
		  	  	  

    }
	 void closeWindow()
	 {
	    WindowAdapter wl = new WindowAdapter()
		 {
		    public void windowClosing(WindowEvent we)
			 {
			    jf_button.dispose();
			 }
		 };
		 jf_button.addWindowListener(wl);	 	 
	 }	  
	 void confirm()
	 {
	    
	    ActionListener al_con = new ActionListener()
		  {
		     public void actionPerformed(ActionEvent e)
			  {
			     if(e.getSource()==jb_confirm)
				  {
				      
						boolean sel1 = jtb_1.isSelected();
						boolean sel2 = jtb_2.isSelected();
						boolean sel3 = jtb_3.isSelected();
						boolean sel4 = jtb_4.isSelected();
						boolean sel5 = jtb_5.isSelected();
						boolean sel6 = jtb_6.isSelected();
						boolean sel7 = jtb_7.isSelected();
						boolean sel8 = jtb_8.isSelected();
						boolean sel9 = jtb_9.isSelected();
						boolean sel10 = jtb_10.isSelected();
						boolean sel11 = jtb_11.isSelected();
						boolean sel12 = jtb_12.isSelected();
						boolean sel13 = jtb_13.isSelected();
						boolean sel14 = jtb_14.isSelected();
						boolean sel15 = jtb_15.isSelected();
						boolean sel16 = jtb_16.isSelected();
						boolean sel17 = jtb_17.isSelected();
						boolean sel18 = jtb_18.isSelected();
						boolean sel19 = jtb_19.isSelected();
						boolean sel20 = jtb_20.isSelected();
						boolean sel21 = jtb_21.isSelected();
						boolean sel22 = jtb_22.isSelected();
						boolean sel23 = jtb_23.isSelected();
						boolean sel24 = jtb_24.isSelected();
						boolean sel25 = jtb_25.isSelected();
						boolean sel26 = jtb_26.isSelected();
						boolean sel27 = jtb_27.isSelected();
						boolean sel28 = jtb_28.isSelected();
						boolean sel29 = jtb_29.isSelected();    
						boolean sel30 = jtb_30.isSelected();  
					   if(sel1 && jtb_1.getText().equals("B")){
						   i++;
						}	
						if(sel2 && jtb_2.getText().equals("B")){
						   i++;
						}
						if(sel3 && jtb_3.getText().equals("B")){
						   i++;}
						if(sel4 && jtb_4.getText().equals("B")){
						   i++;}
						if(sel5 && jtb_5.getText().equals("B"))
						   i++;
						if(sel6 && jtb_6.getText().equals("B"))
						   i++;
						if(sel7 && jtb_7.getText().equals("B"))
						   i++;
						if(sel8 && jtb_8.getText().equals("B"))
						   i++;
						if(sel9 && jtb_9.getText().equals("B"))
						   i++;
						if(sel10 && jtb_10.getText().equals("B"))
						   i++;
						if(sel11 && jtb_11.getText().equals("B"))
						   i++;
						if(sel12 && jtb_12.getText().equals("B"))
						   i++;
						if(sel13 && jtb_13.getText().equals("B"))
						   i++;
						if(sel14 && jtb_14.getText().equals("B"))
						   i++;
						if(sel15 && jtb_15.getText().equals("B"))
						   i++;
						if(sel16 && jtb_16.getText().equals("B"))
						   i++;
						if(sel17 && jtb_17.getText().equals("B"))
						   i++;
						if(sel18 && jtb_18.getText().equals("B"))
						   i++;
						if(sel19 && jtb_19.getText().equals("B"))
						   i++;
						if(sel20 && jtb_20.getText().equals("B"))
						   i++;
						if(sel21 && jtb_21.getText().equals("B"))
						   i++;
						if(sel22 && jtb_22.getText().equals("B"))
						   i++;
						if(sel23 && jtb_23.getText().equals("B"))
						   i++;
						if(sel24 && jtb_24.getText().equals("B"))
						   i++;
						if(sel25 && jtb_25.getText().equals("B"))
						   i++;
						if(sel26 && jtb_26.getText().equals("B"))
						   i++;
						if(sel27 && jtb_27.getText().equals("B"))
						   i++;
						if(sel28 && jtb_28.getText().equals("B"))
						   i++;
						if(sel29 && jtb_29.getText().equals("B"))
						   i++;  
						if(sel30 && jtb_30.getText().equals("B"))
						   i++;
						if(i==0){
						   JOptionPane.showMessageDialog(null,"No tickets were chosen");
							//jt_price.setText("");	  
						}	
					   JOptionPane.showMessageDialog(null,"You have chosen "+i+" ticket(s). Thank you! ");
						closeWindow();
						
					
					}
				}
			};
			jb_confirm.addActionListener(al_con);
  
	 }
}
