//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class card  {
    public JFrame jf;
	 public JPanel jp_card;
    public JLabel jl_cc;
    public JTextField jt_cc1;
    public JLabel jl_cc1;
    public JTextField jt_cc2;
    public JLabel jl_cc2;
    public JTextField jt_cc3;
    public JLabel jl_price;
    public JTextField jt_price;
    public JLabel jl_date;
    public JTextField jt_date;
    public JLabel jl_ctype;
    public JComboBox jcb_cardtype;
    public JLabel jl_cc3;
    public JTextField jt_cc4;
    public JLabel jl_expdate;
    public JComboBox jcb_month;
    public JComboBox jcb_date;
    public JLabel jl_rupeec;
    public JLabel jl_name;
    public JTextField jt_name;
    public JButton jb_pay;
    public JButton jb_cancel;
    public JLabel jl_icici;
    public JLabel jl_expcaption;
    public JLabel jl_cardcaption;
    public JLabel jl_nocaption;
    public JLabel jl_typecaption;
    public JLabel jl_cvv;
    public JTextField jt_cvv;
    public JLabel jcomp30;

    public card() {
        jf = new JFrame();
		  jf.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        jp_card = new JPanel();
		  jf.add(jp_card);    
		  buildGUI();    
		  jf.pack();
        jf.setVisible (true);
		  
		      
		  
    }
    
	 public void bookNow()
	 {
	     //construct preComponents
        String[] jcb_cardtypeItems = {"Maestro	", "MasterCard", "VISA"};
        String[] jcb_monthItems = {"MM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"};
        String[] jcb_dateItems = {"DD", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};

        //construct components
        jl_cc = new JLabel ("Credit Card No:");
        jt_cc1 = new JTextField (1);
        jl_cc1 = new JLabel ("--");
        jt_cc2 = new JTextField (1);
        jl_cc2 = new JLabel ("--");
        jt_cc3 = new JTextField (1);
        jl_price = new JLabel ("Purchase Amount:");
        jt_price = new JTextField (1);
        jl_date = new JLabel ("Date of purchase:");
        jt_date = new JTextField (1);
        jl_ctype = new JLabel ("Card Type:");
        jcb_cardtype = new JComboBox (jcb_cardtypeItems);
        jl_cc3 = new JLabel ("--");
        jt_cc4 = new JTextField (1);
        jl_expdate = new JLabel ("Expiry Date:");
        jcb_month = new JComboBox (jcb_monthItems);
        jcb_date = new JComboBox (jcb_dateItems);
        jl_rupeec = new JLabel ("`");
		  jl_rupeec.setFont(new Font("Rupee Foradian",Font.BOLD,14));
        jl_name = new JLabel ("Name On Card:");
        jt_name = new JTextField (1);
        jb_pay = new JButton ("Pay");
        jb_cancel = new JButton ("Cancel");
        jl_icici = new JLabel (new ImageIcon("icicibank.gif"));
        jl_expcaption = new JLabel ("(Please enter expiry date on your card)");
        jl_cardcaption = new JLabel ("(Please enter the name on your card)");
        jl_nocaption = new JLabel ("(Enter 16 digit no)");
        jl_typecaption = new JLabel ("(Choose card type)");
        jl_cvv = new JLabel ("CVV No:");
        jt_cvv = new JTextField (1);
        jcomp30 = new JLabel ("(Enter the 3 digit CVV No)");

        //set components properties
        jt_price.setEnabled (false);
        jt_date.setEnabled (false);

        //adjust size and set layout
        jp_card.setPreferredSize (new Dimension (560, 435));
        jp_card.setLayout (null);
		  jp_card.setBackground(Color.orange);

        //add components
        jp_card.add (jl_cc);
        jp_card.add (jt_cc1);
        jp_card.add (jl_cc1);
        jp_card.add (jt_cc2);
        jp_card.add (jl_cc2);
        jp_card.add (jt_cc3);
        jp_card.add (jl_price);
        jp_card.add (jt_price);
        jp_card.add (jl_date);
        jp_card.add (jt_date);
        jp_card.add (jl_ctype);
        jp_card.add (jcb_cardtype);
        jp_card.add (jl_cc3);
        jp_card.add (jt_cc4);
        jp_card.add (jl_expdate);
        jp_card.add (jcb_month);
        jp_card.add (jcb_date);
        jp_card.add (jl_rupeec);
        jp_card.add (jl_name);
        jp_card.add (jt_name);
        jp_card.add (jb_pay);
        jp_card.add (jb_cancel);
        jp_card.add (jl_icici);
        jp_card.add (jl_expcaption);
        jp_card.add (jl_cardcaption);
        jp_card.add (jl_nocaption);
        jp_card.add (jl_typecaption);
        jp_card.add (jl_cvv);
        jp_card.add (jt_cvv);
        jp_card.add (jcomp30);

        //set component bounds (only needed by Absolute Positioning)
        jl_cc.setBounds (85, 125, 90, 25);
        jt_cc1.setBounds (195, 125, 40, 25);
        jl_cc1.setBounds (240, 125, 10, 25);
        jt_cc2.setBounds (250, 125, 40, 25);
        jl_cc2.setBounds (295, 125, 10, 25);
        jt_cc3.setBounds (360, 125, 40, 25);
        jl_price.setBounds (85, 215, 110, 25);
        jt_price.setBounds (210, 215, 100, 25);
        jl_date.setBounds (85, 275, 105, 25);
        jt_date.setBounds (195, 275, 100, 25);
        jl_ctype.setBounds (85, 95, 80, 25);
        jcb_cardtype.setBounds (195, 95, 100, 25);
        jl_cc3.setBounds (350, 125, 10, 25);
        jt_cc4.setBounds (305, 125, 40, 25);
        jl_expdate.setBounds (85, 185, 100, 25);
        jcb_month.setBounds (195, 185, 45, 25);
        jcb_date.setBounds (250, 185, 45, 25);
        jl_rupeec.setBounds (200, 215, 15, 25);
        jl_name.setBounds (85, 245, 100, 25);
        jt_name.setBounds (195, 245, 100, 25);
        jb_pay.setBounds (150, 320, 100, 25);
        jb_cancel.setBounds (265, 320, 100, 25);
        jl_icici.setBounds (0, 0, 560, 75);
        jl_expcaption.setBounds (305, 185, 240, 25);
        jl_cardcaption.setBounds (305, 245, 215, 25);
        jl_nocaption.setBounds (405, 125, 100, 25);
        jl_typecaption.setBounds (305, 95, 115, 25);
        jl_cvv.setBounds (85, 155, 100, 25);
        jt_cvv.setBounds (195, 155, 45, 25);
        jcomp30.setBounds (245, 155, 170, 25);
    }
	 
    public static void main (String[] args) {
        new card();
        
    }
}
