use ipl;
delete from entertainment;
insert into entertainment 
values(1,'b'),
      (2,null) ,
      (3,null)  ,
      (4,'b')   ,
      (5,null)    ,
      (6,null)     ,
      (7,'b')      ,
      (8,null)       ,
      (9,null)        ,
      (10,'b')        ,
      (11,null)         ,
      (12,null)          ,
      (13,'b')           ,
      (14,null)            ,
      (15,'b')             ,
      (16,null)              ,
      (17,null)               ,
      (18,'b')                ,
      (19,'b')                 ,
      (20,null)                  ,
      (21,null)                   ,
      (22,'b')                    ,
      (23,null)                     ,
      (24,'b')                      ,
      (25,null)                       ,
      (26,'b')                        ,
      (27,'b')                         ,
      (28,null)                          ,
      (29,'b')                           ,
      (30,null)
       