use ipl;
delete from standc;

insert into standc 
values(1,null),
      (2,null) ,
      (3,'b')  ,
      (4,null)   ,
      (5,'b')    ,
      (6,null)     ,
      (7,null)      ,
      (8,'b')       ,
      (9,null)        ,
      (10,null)        ,
      (11,'b')         ,
      (12,null)          ,
      (13,'b')           ,
      (14,null)            ,
      (15,null)             ,
      (16,'b')              ,
      (17,null)               ,
      (18,null)                ,
      (19,'b')                 ,
      (20,null)                  ,
      (21,null)                   ,
      (22,null)                    ,
      (23,'b')                     ,
      (24,null)                      ,
      (25,'b')                       ,
      (26,null)                        ,
      (27,null)                         ,
      (28,'b')                          ,
      (29,'b')                           ,
      (30,null)
       