insert into celebrity 
values		(1,null),
      		(2,null),
      		(3,null),
      		(4,'b'),
      		(5,null),
      		(6,null),
      		(7,'b'),
          (8,null),
      		(9,null),
      		(10,'b'),
      		(11,null),
      		(12,'b'),
      		(13,null),
      		(14,null),
      		(15,'b'),
      		(16,null),
      		(17,null),
      		(18,'b'),
      		(19,null),
      		(20,null),
      		(21,'b'),
      		(22,null),
      		(23,null),
      		(24,'b'),
      		(25,null),
      		(26,null),
      		(27,'b'),
      		(28,null),
      		(29,'b'),
      		(30,null)
       