//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class kkr {
    private JLabel sp_kkr;
    private JTextArea jta_kkr;
    private JTextArea jta_supkkr;
    private JFrame jf_kkr;
	 private JPanel jp_kkr;
	 private JScrollPane kkr_det, kkr_sup;

    public kkr() {
	     jf_kkr = new JFrame("Kolkatta Knight Riders");
		  jf_kkr.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        jp_kkr = new JPanel();    
		  jf_kkr.add(jp_kkr);    
		  
        buildKKR();
		  jf_kkr.pack();    
		  jf_kkr.setVisible (true);
    }
	 
	 void buildKKR()
	 {
	       //construct components
        sp_kkr = new JLabel (new ImageIcon("KKR_teamLogo.gif"));
        jta_kkr = new JTextArea (5, 5);
        jta_supkkr = new JTextArea (5, 5);
		  jta_kkr.setText("When Shahrukh Khan - India's biggest movie star - co-purchased the Kolkata Knight Riders\n"+
		  "franchise, the nation couldn't help but feel an affinity with the side.\n" +
		   "And when Brendon McCullum stormed into the competition with a whirlwind 158*,\n"+ 
			"it drew a collective gasp of admiration from fans of the sport across the world.\n" + 
			"If Sourav helmed the side, then there was John Buchanan who powered the think-tank.\n"+ 
			"But the team could not live up to expectations.\n " +

        "In the second season, suggestions of a multiple-captain approach drew a lot of debate \n"+
		  "but as it turned out, McCullum ended up leading the side throughout. But the side's \n"+
		  "prospects did not improve. KKR ended the tournament pretty close to the bottom of the table.\n"+
		  "Ricky Ponting and Morne van Wyk have been bought out ahead of Season 2010, while Shane Bond\n" +
		  "has been bought at USD 750,000. U-19 player Harpreet Singh has also been picked for the\n"+
		  " tournament."); 
        jta_supkkr.setText("Support Staff:\n"+

                            "Dave Whatmore\n"+ 
                            "Wasim Akram\n"+ 
                            "Andrew Leipus\n"+ 
                            "Adrian Le");     
		  kkr_det = new JScrollPane(jta_kkr);
		  kkr_sup = new JScrollPane(jta_supkkr);
        //adjust size and set layout
        jp_kkr.setPreferredSize (new Dimension (560, 435));
        jp_kkr.setLayout (null);

        //add components
        jp_kkr.add (sp_kkr);
        jp_kkr.add (kkr_det);
        jp_kkr.add (kkr_sup);

        //set component bounds (only needed by Absolute Positioning)
        sp_kkr.setBounds (20, 185, 170, 145);
        kkr_det.setBounds (20, 15, 505, 165);
        kkr_sup.setBounds (350, 190, 175, 150);
    }

    public static void main (String[] args) {
	     new kkr();
        
    }
}
