//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class mi extends JPanel {
    private JLabel sp_mi;
    private JTextArea jta_mi;
    private JTextArea jta_supmi;

    public mi() {
        //construct components
        sp_mi = new JLabel ("pic");
        jta_mi = new JTextArea (5, 5);
        jta_supmi = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (560, 435));
        setLayout (null);

        //add components
        add (sp_mi);
        add (jta_mi);
        add (jta_supmi);

        //set component bounds (only needed by Absolute Positioning)
        sp_mi.setBounds (20, 185, 170, 145);
        jta_mi.setBounds (20, 15, 505, 165);
        jta_supmi.setBounds (350, 185, 175, 150);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("mi");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new mi());
        frame.pack();
        frame.setVisible (true);
    }
}
