//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class rcb extends JPanel {
    private JLabel sp_rcb;
    private JTextArea jta_rcb;
    private JTextArea jta_suprcb;

    public rcb() {
        //construct components
        sp_rcb = new JLabel ("pic");
        jta_rcb = new JTextArea (5, 5);
        jta_suprcb = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (560, 435));
        setLayout (null);

        //add components
        add (sp_rcb);
        add (jta_rcb);
        add (jta_suprcb);

        //set component bounds (only needed by Absolute Positioning)
        sp_rcb.setBounds (20, 185, 170, 145);
        jta_rcb.setBounds (20, 15, 505, 165);
        jta_suprcb.setBounds (350, 185, 175, 150);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("rcb");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new rcb());
        frame.pack();
        frame.setVisible (true);
    }
}
