//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class dc
{
    public JLabel sp_dc;
    public JTextArea jta_dc;
    public JTextArea jta_supdc;
    public JTextArea jta_dcsq;

    public dc() {
        //construct components
        sp_dc = new JLabel ("pic");
        jta_dc = new JTextArea (5, 5);
        jta_supdc = new JTextArea (5, 5);
        jta_dcsq = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (560, 435));
        setLayout (null);

        //add components
        add (sp_dc);
        add (jta_dc);
        add (jta_supdc);
        add (jta_dcsq);

        //set component bounds (only needed by Absolute Positioning)
        sp_dc.setBounds (105, 40, 190, 180);
        jta_dc.setBounds (45, 235, 315, 155);
        jta_supdc.setBounds (380, 235, 130, 155);
        jta_dcsq.setBounds (380, 40, 130, 185);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("dc");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new dc());
        frame.pack();
        frame.setVisible (true);
    }
}
