//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Success  {
	 JFrame frame;
	 JPanel jp_sucpay;
    private JLabel jl_success;
    private JLabel jl_clicksave;
    private JLabel jl_clickpre;
    private JButton jb_preview;
    private JButton jbtns_dome;
    private JButton jb_print;
    private JLabel jl_iciciadv;

    public Success() {
	     frame = new JFrame ("success");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
		  jp_sucpay = new JPanel();
		  frame.add(jp_sucpay);
        successPay();
		  frame.pack();
        frame.setVisible (true);
        
    }
    
	 void successPay()
	 {
	    //construct components
        jl_success = new JLabel ("Transaction successful. Booking completed. ");
        jl_clicksave = new JLabel ("Click save to save your ticket as a pdf file to be printed later.");
        jl_clickpre = new JLabel ("Click Preview to preview your ticket.");
        jb_preview = new JButton ("Preview");
        jbtns_dome = new JButton ("Home");
        jb_print = new JButton ("Print");
        jl_iciciadv = new JLabel (new ImageIcon("icicibank.gif"));

        //adjust size and set layout
        jp_sucpay.setPreferredSize (new Dimension (560, 435));
        jp_sucpay.setLayout (null);

        //add components
        jp_sucpay.add (jl_success);
        jp_sucpay.add (jl_clicksave);
        jp_sucpay.add (jl_clickpre);
        jp_sucpay.add (jb_preview);
        jp_sucpay.add (jbtns_dome);
        jp_sucpay.add (jb_print);
        jp_sucpay.add (jl_iciciadv);

        //set component bounds (only needed by Absolute Positioning)
        jl_success.setBounds (90, 100, 265, 30);
        jl_clicksave.setBounds (90, 135, 340, 30);
        jl_clickpre.setBounds (90, 165, 225, 30);
        jb_preview.setBounds (90, 205, 100, 25);
        jbtns_dome.setBounds (310, 205, 100, 25);
        jb_print.setBounds (200, 205, 100, 25);
        jl_iciciadv.setBounds (0, 0, 560, 80);
    }
	 
    public static void main (String[] args) {
        new Success();
    }
}
