//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Button extends JPanel {
    private JButton jb_7;
    private JButton jb_8;
    private JButton jb_3;
    private JButton jb_14;
    private JButton jb_2;
    private JButton jb_1;
    private JButton jb_4;
    private JButton jb_10;
    private JButton jb_11;
    private JButton jb_6;
    private JButton jb_5;
    private JButton jb_17;
    private JButton jb_19;
    private JButton jb_13;
    private JButton jb_9;
    private JButton jb_15;
    private JButton jb_12;
    private JButton jb_16;
    private JButton jb_25;
    private JButton jb_20;
    private JButton jb_23;
    private JButton jb_22;
    private JButton jb_18;
    private JButton jb_21;
    private JButton jb_24;
    private JButton jb_26;
    private JButton jb_27;
    private JButton jb_28;
    private JButton jb_29;
    private JButton jb_30;
    private JButton jb_31;

    public Button() {
        //construct components
        jb_7 = new JButton ("");
        jb_8 = new JButton ("");
        jb_3 = new JButton ("");
        jb_14 = new JButton ("");
        jb_2 = new JButton ("");
        jb_1 = new JButton ("");
        jb_4 = new JButton ("");
        jb_10 = new JButton ("");
        jb_11 = new JButton ("");
        jb_6 = new JButton ("");
        jb_5 = new JButton ("");
        jb_17 = new JButton ("");
        jb_19 = new JButton ("");
        jb_13 = new JButton ("");
        jb_9 = new JButton ("");
        jb_15 = new JButton ("");
        jb_12 = new JButton ("");
        jb_16 = new JButton ("");
        jb_25 = new JButton ("");
        jb_20 = new JButton ("");
        jb_23 = new JButton ("");
        jb_22 = new JButton ("");
        jb_18 = new JButton ("");
        jb_21 = new JButton ("");
        jb_24 = new JButton ("");
        jb_26 = new JButton ("");
        jb_27 = new JButton ("");
        jb_28 = new JButton ("");
        jb_29 = new JButton ("");
        jb_30 = new JButton ("");
        jb_31 = new JButton ("Confirm..!!");

        //adjust size and set layout
        setPreferredSize (new Dimension (496, 371));
        setLayout (null);

        //add components
        add (jb_7);
        add (jb_8);
        add (jb_3);
        add (jb_14);
        add (jb_2);
        add (jb_1);
        add (jb_4);
        add (jb_10);
        add (jb_11);
        add (jb_6);
        add (jb_5);
        add (jb_17);
        add (jb_19);
        add (jb_13);
        add (jb_9);
        add (jb_15);
        add (jb_12);
        add (jb_16);
        add (jb_25);
        add (jb_20);
        add (jb_23);
        add (jb_22);
        add (jb_18);
        add (jb_21);
        add (jb_24);
        add (jb_26);
        add (jb_27);
        add (jb_28);
        add (jb_29);
        add (jb_30);
        add (jb_31);

        //set component bounds (only needed by Absolute Positioning)
        jb_7.setBounds (120, 95, 30, 30);
        jb_8.setBounds (155, 95, 30, 30);
        jb_3.setBounds (190, 55, 30, 30);
        jb_14.setBounds (155, 135, 30, 30);
        jb_2.setBounds (155, 55, 30, 30);
        jb_1.setBounds (120, 55, 30, 30);
        jb_4.setBounds (225, 55, 30, 30);
        jb_10.setBounds (225, 95, 30, 30);
        jb_11.setBounds (260, 95, 30, 30);
        jb_6.setBounds (295, 55, 30, 30);
        jb_5.setBounds (260, 55, 30, 30);
        jb_17.setBounds (260, 135, 30, 30);
        jb_19.setBounds (120, 175, 30, 30);
        jb_13.setBounds (120, 135, 30, 30);
        jb_9.setBounds (190, 95, 30, 30);
        jb_15.setBounds (190, 135, 30, 30);
        jb_12.setBounds (295, 95, 30, 30);
        jb_16.setBounds (225, 135, 30, 30);
        jb_25.setBounds (120, 215, 30, 30);
        jb_20.setBounds (155, 175, 30, 30);
        jb_23.setBounds (260, 175, 30, 30);
        jb_22.setBounds (225, 175, 30, 30);
        jb_18.setBounds (295, 135, 30, 30);
        jb_21.setBounds (190, 175, 30, 30);
        jb_24.setBounds (295, 175, 30, 30);
        jb_26.setBounds (155, 215, 30, 30);
        jb_27.setBounds (190, 215, 30, 30);
        jb_28.setBounds (225, 215, 30, 30);
        jb_29.setBounds (260, 215, 30, 30);
        jb_30.setBounds (295, 215, 30, 30);
        jb_31.setBounds (190, 265, 130, 35);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("30 Button");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Button());
        frame.pack();
        frame.setVisible (true);
    }
}
