//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Button {
    JFrame jf;
    JPanel jp_button;
    public JToggleButton jb_7;
    public JToggleButton jb_8;
    public JToggleButton jb_3;
    public JToggleButton jb_14;
    public JToggleButton jb_2;
    public JToggleButton jb_1;
    public JToggleButton jb_4;
    public JToggleButton jb_10;
    public JToggleButton jb_11;
    public JToggleButton jb_6;
    public JToggleButton jb_5;
    public JToggleButton jb_17;
    public JToggleButton jb_19;
    public JToggleButton jb_13;
    public JToggleButton jb_9;
    public JToggleButton jb_15;
    public JToggleButton jb_12;
    public JToggleButton jb_16;
    public JToggleButton jb_25;
    public JToggleButton jb_20;
    public JToggleButton jb_23;
    public JToggleButton jb_22;
    public JToggleButton jb_18;
    public JToggleButton jb_21;
    public JToggleButton jb_24;
    public JToggleButton jb_26;
    public JToggleButton jb_27;
    public JToggleButton jb_28;
    public JToggleButton jb_29;
    public JToggleButton jb_30;
    public JToggleButton jb_31;

    public Button() {
	     jf = new JFrame();
		  jf.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        jp_button = new JPanel();
		  jf.add(jp_button);
	     buttons();
		  jf.pack();
        jf.setVisible (true);
		  
    }
	 public void buttons()
	 {
	    
        //construct components
        jb_7 = new JToggleButton ("");
        jb_8 = new JToggleButton ("");
        jb_3 = new JToggleButton ("");
        jb_14 = new JToggleButton ("");
        jb_2 = new JToggleButton ("");
        jb_1 = new JToggleButton ("");
        jb_4 = new JToggleButton ("");
        jb_10 = new JToggleButton ("");
        jb_11 = new JToggleButton ("");
        jb_6 = new JToggleButton ("");
        jb_5 = new JToggleButton ("");
        jb_17 = new JToggleButton ("");
        jb_19 = new JToggleButton ("");
        jb_13 = new JToggleButton ("");
        jb_9 = new JToggleButton ("");
        jb_15 = new JToggleButton ("");
        jb_12 = new JToggleButton ("");
        jb_16 = new JToggleButton ("");
        jb_25 = new JToggleButton ("");
        jb_20 = new JToggleButton ("");
        jb_23 = new JToggleButton ("");
        jb_22 = new JToggleButton ("");
        jb_18 = new JToggleButton ("");
        jb_21 = new JToggleButton ("");
        jb_24 = new JToggleButton ("");
        jb_26 = new JToggleButton ("");
        jb_27 = new JToggleButton ("");
        jb_28 = new JToggleButton ("");
        jb_29 = new JToggleButton ("");
        jb_30 = new JToggleButton ("");
        jb_31 = new JToggleButton ("Confirm");

        //adjust size and set layout
        jp_button.setPreferredSize (new Dimension (496, 371));
        jp_button.setLayout (null);

        //add components
        jp_button.add (jb_7);
        jp_button.add (jb_8);
        jp_button.add (jb_3);
        jp_button.add (jb_14);
        jp_button.add (jb_2);
        jp_button.add (jb_1);
        jp_button.add (jb_4);
        jp_button.add (jb_10);
        jp_button.add (jb_11);
        jp_button.add (jb_6);
        jp_button.add (jb_5);
        jp_button.add (jb_17);
        jp_button.add (jb_19);
        jp_button.add (jb_13);
        jp_button.add (jb_9);
        jp_button.add (jb_15);
        jp_button.add (jb_12);
        jp_button.add (jb_16);
        jp_button.add (jb_25);
        jp_button.add (jb_20);
        jp_button.add (jb_23);
        jp_button.add (jb_22);
        jp_button.add (jb_18);
        jp_button.add (jb_21);
        jp_button.add (jb_24);
        jp_button.add (jb_26);
        jp_button.add (jb_27);
        jp_button.add (jb_28);
        jp_button.add (jb_29);
        jp_button.add (jb_30);
        jp_button.add (jb_31);

        //set component bounds (only needed by Absolute Positioning)
        jb_7.setBounds (120, 95, 30, 30);
        jb_8.setBounds (155, 95, 30, 30);
        jb_3.setBounds (190, 55, 30, 30);
        jb_14.setBounds (155, 135, 30, 30);
        jb_2.setBounds (155, 55, 30, 30);
        jb_1.setBounds (120, 55, 45, 30);
        jb_4.setBounds (225, 55, 30, 30);
        jb_10.setBounds (225, 95, 30, 30);
        jb_11.setBounds (260, 95, 30, 30);
        jb_6.setBounds (295, 55, 30, 30);
        jb_5.setBounds (260, 55, 30, 30);
        jb_17.setBounds (260, 135, 30, 30);
        jb_19.setBounds (120, 175, 30, 30);
        jb_13.setBounds (120, 135, 30, 30);
        jb_9.setBounds (190, 95, 30, 30);
        jb_15.setBounds (190, 135, 30, 30);
        jb_12.setBounds (295, 95, 30, 30);
        jb_16.setBounds (225, 135, 30, 30);
        jb_25.setBounds (120, 215, 30, 30);
        jb_20.setBounds (155, 175, 30, 30);
        jb_23.setBounds (260, 175, 30, 30);
        jb_22.setBounds (225, 175, 30, 30);
        jb_18.setBounds (295, 135, 30, 30);
        jb_21.setBounds (190, 175, 30, 30);
        jb_24.setBounds (295, 175, 30, 30);
        jb_26.setBounds (155, 215, 30, 30);
        jb_27.setBounds (190, 215, 30, 30);
        jb_28.setBounds (225, 215, 30, 30);
        jb_29.setBounds (260, 215, 30, 30);
        jb_30.setBounds (295, 215, 30, 30);
        jb_31.setBounds (190, 265, 130, 35);
		  
		  ActionListener al = new ActionListener()
		  {
		     public void actionPerformed(ActionEvent e)
			  {
			     if(e.getSource()==jb_1)
				  {
				     jb_1.setText("B");
					  jb_1.setBackground(Color.red);
					  jb_1.setEnabled(false);
				  }
			  }
		  };
		  jb_1.addActionListener(al);	  	  	  

    }
    public static void main (String[] args) {
        new Button();
       
    }
}
