//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Button {
    public JToggleButton jtb_1;
    public JToggleButton jtb_2;
    public JToggleButton jtb_3;
    public JToggleButton jtb_4;
    public JToggleButton jtb_5;
    public JToggleButton jtb_6;
    public JToggleButton jtb_7;
    public JToggleButton jtb_8;
    public JToggleButton jtb_9;
    public JToggleButton jtb_10;
    public JToggleButton jtb_11;
    public JToggleButton jtb_12;
    public JToggleButton jtb_13;
    public JToggleButton jtb_14;
    public JToggleButton jtb_15;
    public JToggleButton jtb_16;
    public JToggleButton jtb_17;
    public JToggleButton jtb_18;
    public JToggleButton jtb_19;
    public JToggleButton jtb_20;
    public JToggleButton jtb_21;
    public JToggleButton jtb_22;
    public JToggleButton jtb_23;
    public JToggleButton jtb_24;
    public JToggleButton jtb_25;
    public JToggleButton jtb_26;
    public JToggleButton jtb_27;
    public JToggleButton jtb_28;
    public JToggleButton jtb_29;
    public JToggleButton jtb_30;
    public JButton jb_confirm;

    public Button() {
	     jf = new JFrame();
		  jf.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        jp_button = new JPanel();
		  jf.add(jp_button);
	     buttons();
		  jf.pack();
        jf.setVisible (true);
		  
    }
    void buttons()
	 {
	     //construct components
        jtb_1 = new JToggleButton ("", false);
        jtb_2 = new JToggleButton ("", false);
        jtb_3 = new JToggleButton ("", false);
        jtb_4 = new JToggleButton ("", false);
        jtb_5 = new JToggleButton ("", false);
        jtb_6 = new JToggleButton ("", false);
        jtb_7 = new JToggleButton ("", false);
        jtb_8 = new JToggleButton ("", false);
        jtb_9 = new JToggleButton ("", false);
        jtb_10 = new JToggleButton ("", false);
        jtb_11 = new JToggleButton ("", false);
        jtb_12 = new JToggleButton ("", false);
        jtb_13 = new JToggleButton ("", false);
        jtb_14 = new JToggleButton ("", false);
        jtb_15 = new JToggleButton ("", false);
        jtb_16 = new JToggleButton ("", false);
        jtb_17 = new JToggleButton ("", false);
        jtb_18 = new JToggleButton ("", false);
        jtb_19 = new JToggleButton ("", false);
        jtb_20 = new JToggleButton ("", false);
        jtb_21 = new JToggleButton ("", false);
        jtb_22 = new JToggleButton ("", false);
        jtb_23 = new JToggleButton ("", false);
        jtb_24 = new JToggleButton ("", false);
        jtb_25 = new JToggleButton ("", false);
        jtb_26 = new JToggleButton ("", false);
        jtb_27 = new JToggleButton ("", false);
        jtb_28 = new JToggleButton ("", false);
        jtb_29 = new JToggleButton ("", false);
        jtb_30 = new JToggleButton ("", false);
        jb_confirm = new JButton ("Confirm");

        //adjust size and set layout
        jp_button.setPreferredSize (new Dimension (560, 435));
        jp_button.setLayout (null);

        //add components
        jp_button.add (jtb_1);
        jp_button.add (jtb_2);
        jp_button.add (jtb_3);
        jp_button.add (jtb_4);
        jp_button.add (jtb_5);
        jp_button.add (jtb_6);
        jp_button.add (jtb_7);
        jp_button.add (jtb_8);
        jp_button.add (jtb_9);
        jp_button.add (jtb_10);
        jp_button.add (jtb_11);
        jp_button.add (jtb_12);
        jp_button.add (jtb_13);
        jp_button.add (jtb_14);
        jp_button.add (jtb_15);
        jp_button.add (jtb_16);
        jp_button.add (jtb_17);
        jp_button.add (jtb_18);
        jp_button.add (jtb_19);
        jp_button.add (jtb_20);
        jp_button.add (jtb_21);
        jp_button.add (jtb_22);
        jp_button.add (jtb_23);
        jp_button.add (jtb_24);
        jp_button.add (jtb_25);
        jp_button.add (jtb_26);
        jp_button.add (jtb_27);
        jp_button.add (jtb_28);
        jp_button.add (jtb_29);
        jp_button.add (jtb_30);
        jp_button.add (jb_confirm);

        //set component bounds (only needed by Absolute Positioning)
        jtb_1.setBounds (100, 65, 45, 40);
        jtb_2.setBounds (150, 65, 45, 40);
        jtb_3.setBounds (200, 65, 45, 40);
        jtb_4.setBounds (250, 65, 45, 40);
        jtb_5.setBounds (300, 65, 45, 40);
        jtb_6.setBounds (350, 65, 45, 40);
        jtb_7.setBounds (100, 110, 45, 40);
        jtb_8.setBounds (150, 110, 45, 40);
        jtb_9.setBounds (200, 110, 45, 40);
        jtb_10.setBounds (250, 110, 45, 40);
        jtb_11.setBounds (300, 110, 45, 40);
        jtb_12.setBounds (350, 110, 45, 40);
        jtb_13.setBounds (100, 155, 45, 40);
        jtb_14.setBounds (150, 155, 45, 40);
        jtb_15.setBounds (200, 155, 45, 40);
        jtb_16.setBounds (250, 155, 45, 40);
        jtb_17.setBounds (300, 155, 45, 40);
        jtb_18.setBounds (350, 155, 45, 40);
        jtb_19.setBounds (100, 200, 45, 40);
        jtb_20.setBounds (150, 200, 45, 40);
        jtb_21.setBounds (200, 200, 45, 40);
        jtb_22.setBounds (250, 200, 45, 40);
        jtb_23.setBounds (300, 200, 45, 40);
        jtb_24.setBounds (350, 200, 45, 40);
        jtb_25.setBounds (100, 245, 45, 40);
        jtb_26.setBounds (150, 245, 45, 40);
        jtb_27.setBounds (200, 245, 45, 40);
        jtb_28.setBounds (250, 245, 45, 40);
        jtb_29.setBounds (300, 245, 45, 40);
        jtb_30.setBounds (350, 245, 45, 40);
        jb_confirm.setBounds (200, 300, 95, 30);  
		 
		  ActionListener al = new ActionListener()
		  {
		     public void actionPerformed(ActionEvent e)
			  {
			     if(e.getSource()==jb_1)
				  {
				     jb_1.setText("B");
					  jb_1.setBackground(Color.red);
					  jb_1.setEnabled(false);
				  }
			  }
		  };
		  jb_1.addActionListener(al);
	 }	  

    public static void main (String[] args) {
       new Button();
    }
}
