//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Button {
    JFrame jf_button;
	 JPanel jp_button;
    public JToggleButton jtb_1;
    public JToggleButton jtb_2;
    public JToggleButton jtb_3;
    public JToggleButton jtb_4;
    public JToggleButton jtb_5;
    public JToggleButton jtb_6;
    public JToggleButton jtb_7;
    public JToggleButton jtb_8;
    public JToggleButton jtb_9;
    public JToggleButton jtb_10;
    public JToggleButton jtb_11;
    public JToggleButton jtb_12;
    public JToggleButton jtb_13;
    public JToggleButton jtb_14;
    public JToggleButton jtb_15;
    public JToggleButton jtb_16;
    public JToggleButton jtb_17;
    public JToggleButton jtb_18;
    public JToggleButton jtb_19;
    public JToggleButton jtb_20;
    public JToggleButton jtb_21;
    public JToggleButton jtb_22;
    public JToggleButton jtb_23;
    public JToggleButton jtb_24;
    public JToggleButton jtb_25;
    public JToggleButton jtb_26;
    public JToggleButton jtb_27;
    public JToggleButton jtb_28;
    public JToggleButton jtb_29;
    public JToggleButton jtb_30;
    public JButton jb_confirm;

    public Button() {
	     jf_button = new JFrame();
		  jf_button.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        jp_button = new JPanel();
		  jf_button.add(jp_button);
	     buttons();
		  jf_button.pack();
        jf_button.setVisible (true);
		  
    }
    void buttons()
	 {
	     //construct components
        jtb_1 = new JToggleButton ("", false);
        jtb_2 = new JToggleButton ("", false);
        jtb_3 = new JToggleButton ("", false);
        jtb_4 = new JToggleButton ("", false);
        jtb_5 = new JToggleButton ("", false);
        jtb_6 = new JToggleButton ("", false);
        jtb_7 = new JToggleButton ("", false);
        jtb_8 = new JToggleButton ("", false);
        jtb_9 = new JToggleButton ("", false);
        jtb_10 = new JToggleButton ("", false);
        jtb_11 = new JToggleButton ("", false);
        jtb_12 = new JToggleButton ("", false);
        jtb_13 = new JToggleButton ("", false);
        jtb_14 = new JToggleButton ("", false);
        jtb_15 = new JToggleButton ("", false);
        jtb_16 = new JToggleButton ("", false);
        jtb_17 = new JToggleButton ("", false);
        jtb_18 = new JToggleButton ("", false);
        jtb_19 = new JToggleButton ("", false);
        jtb_20 = new JToggleButton ("", false);
        jtb_21 = new JToggleButton ("", false);
        jtb_22 = new JToggleButton ("", false);
        jtb_23 = new JToggleButton ("", false);
        jtb_24 = new JToggleButton ("", false);
        jtb_25 = new JToggleButton ("", false);
        jtb_26 = new JToggleButton ("", false);
        jtb_27 = new JToggleButton ("", false);
        jtb_28 = new JToggleButton ("", false);
        jtb_29 = new JToggleButton ("", false);
        jtb_30 = new JToggleButton ("", false);
        jb_confirm = new JButton ("Confirm");

        //adjust size and set layout
        jp_button.setPreferredSize (new Dimension (560, 435));
        jp_button.setLayout (null);

        //add components
        jp_button.add (jtb_1);
        jp_button.add (jtb_2);
        jp_button.add (jtb_3);
        jp_button.add (jtb_4);
        jp_button.add (jtb_5);
        jp_button.add (jtb_6);
        jp_button.add (jtb_7);
        jp_button.add (jtb_8);
        jp_button.add (jtb_9);
        jp_button.add (jtb_10);
        jp_button.add (jtb_11);
        jp_button.add (jtb_12);
        jp_button.add (jtb_13);
        jp_button.add (jtb_14);
        jp_button.add (jtb_15);
        jp_button.add (jtb_16);
        jp_button.add (jtb_17);
        jp_button.add (jtb_18);
        jp_button.add (jtb_19);
        jp_button.add (jtb_20);
        jp_button.add (jtb_21);
        jp_button.add (jtb_22);
        jp_button.add (jtb_23);
        jp_button.add (jtb_24);
        jp_button.add (jtb_25);
        jp_button.add (jtb_26);
        jp_button.add (jtb_27);
        jp_button.add (jtb_28);
        jp_button.add (jtb_29);
        jp_button.add (jtb_30);
        jp_button.add (jb_confirm);

        //set component bounds (only needed by Absolute Positioning)
        jtb_1.setBounds (100, 65, 45, 40);
        jtb_2.setBounds (150, 65, 45, 40);
        jtb_3.setBounds (200, 65, 45, 40);
        jtb_4.setBounds (250, 65, 45, 40);
        jtb_5.setBounds (300, 65, 45, 40);
        jtb_6.setBounds (350, 65, 45, 40);
        jtb_7.setBounds (100, 110, 45, 40);
        jtb_8.setBounds (150, 110, 45, 40);
        jtb_9.setBounds (200, 110, 45, 40);
        jtb_10.setBounds (250, 110, 45, 40);
        jtb_11.setBounds (300, 110, 45, 40);
        jtb_12.setBounds (350, 110, 45, 40);
        jtb_13.setBounds (100, 155, 45, 40);
        jtb_14.setBounds (150, 155, 45, 40);
        jtb_15.setBounds (200, 155, 45, 40);
        jtb_16.setBounds (250, 155, 45, 40);
        jtb_17.setBounds (300, 155, 45, 40);
        jtb_18.setBounds (350, 155, 45, 40);
        jtb_19.setBounds (100, 200, 45, 40);
        jtb_20.setBounds (150, 200, 45, 40);
        jtb_21.setBounds (200, 200, 45, 40);
        jtb_22.setBounds (250, 200, 45, 40);
        jtb_23.setBounds (300, 200, 45, 40);
        jtb_24.setBounds (350, 200, 45, 40);
        jtb_25.setBounds (100, 245, 45, 40);
        jtb_26.setBounds (150, 245, 45, 40);
        jtb_27.setBounds (200, 245, 45, 40);
        jtb_28.setBounds (250, 245, 45, 40);
        jtb_29.setBounds (300, 245, 45, 40);
        jtb_30.setBounds (350, 245, 45, 40);
        jb_confirm.setBounds (200, 300, 95, 30);  
		 
		  ActionListener al = new ActionListener()
		  {
		     public void actionPerformed(ActionEvent e)
			  {
			     if(e.getSource()==jtb_1)
				  {
				     jtb_1.setText("B");
					  jtb_1.setBackground(Color.red);
					  jtb_1.setEnabled(false);
				  }
				  if(e.getSource()==jtb_2)
				  {
				     jtb_2.setText("B");
					  jtb_2.setBackground(Color.red);
					  jtb_2.setEnabled(false);
				  }
				  if(e.getSource()==jtb_3)
				  {
				     jtb_3.setText("B");
					  jtb_3.setBackground(Color.red);
					  jtb_3.setEnabled(false);
				  }
				  if(e.getSource()==jtb_4)
				  {
				     jtb_4.setText("B");
					  jtb_4.setBackground(Color.red);
					  jtb_4.setEnabled(false);
				  }
				  if(e.getSource()==jtb_5)
				  {
				     jtb_5.setText("B");
					  jtb_5.setBackground(Color.red);
					  jtb_5.setEnabled(false);
				  }
				  if(e.getSource()==jtb_6)
				  {
				     jtb_6.setText("B");
					  jtb_6.setBackground(Color.red);
					  jtb_6.setEnabled(false);
				  }
				  
				  if(e.getSource()==jtb_7)
				  {
				     jtb_7.setText("B");
					  jtb_7.setBackground(Color.red);
					  jtb_7.setEnabled(false);
				  }
				  if(e.getSource()==jtb_8)
				  {
				     jtb_8.setText("B");
					  jtb_8.setBackground(Color.red);
					  jtb_8.setEnabled(false);
				  }
				  if(e.getSource()==jtb_9)
				  {
				     jtb_9.setText("B");
					  jtb_9.setBackground(Color.red);
					  jtb_9.setEnabled(false);
				  }
				  if(e.getSource()==jtb_10)
				  {
				     jtb_10.setText("B");
					  jtb_10.setBackground(Color.red);
					  jtb_10.setEnabled(false);
				  }
				  if(e.getSource()==jtb_11)
				  {
				     jtb_11.setText("B");
					  jtb_11.setBackground(Color.red);
					  jtb_11.setEnabled(false);
				  }
				  if(e.getSource()==jtb_12)
				  {
				     jtb_12.setText("B");
					  jtb_12.setBackground(Color.red);
					  jtb_12.setEnabled(false);
				  }
				  if(e.getSource()==jtb_13)
				  {
				     jtb_13.setText("B");
					  jtb_13.setBackground(Color.red);
					  jtb_13.setEnabled(false);
				  }
				  if(e.getSource()==jtb_14)
				  {
				     jtb_14.setText("B");
					  jtb_14.setBackground(Color.red);
					  jtb_14.setEnabled(false);
				  }
				  if(e.getSource()==jtb_15)
				  {
				     jtb_15.setText("B");
					  jtb_15.setBackground(Color.red);
					  jtb_15.setEnabled(false);
				  }
				  if(e.getSource()==jtb_16)
				  {
				     jtb_16.setText("B");
					  jtb_16.setBackground(Color.red);
					  jtb_16.setEnabled(false);
				  }
				  if(e.getSource()==jtb_17)
				  {
				     jtb_17.setText("B");
					  jtb_17.setBackground(Color.red);
					  jtb_17.setEnabled(false);
				  }
				  if(e.getSource()==jtb_18)
				  {
				     jtb_18.setText("B");
					  jtb_18.setBackground(Color.red);
					  jtb_18.setEnabled(false);
				  }
				  if(e.getSource()==jtb_19)
				  {
				     jtb_19.setText("B");
					  jtb_19.setBackground(Color.red);
					  jtb_19.setEnabled(false);
				  }
				  if(e.getSource()==jtb_20)
				  {
				     jtb_20.setText("B");
					  jtb_20.setBackground(Color.red);
					  jtb_20.setEnabled(false);
				  }
				  if(e.getSource()==jtb_21)
				  {
				     jtb_21.setText("B");
					  jtb_21.setBackground(Color.red);
					  jtb_21.setEnabled(false);
				  }
				  if(e.getSource()==jtb_22)
				  {
				     jtb_22.setText("B");
					  jtb_22.setBackground(Color.red);
					  jtb_22.setEnabled(false);
				  }
				  if(e.getSource()==jtb_23)
				  {
				     jtb_23.setText("B");
					  jtb_23.setBackground(Color.red);
					  jtb_23.setEnabled(false);
				  }
				  
				  if(e.getSource()==jtb_24)
				  {
				     jtb_24.setText("B");
					  jtb_24.setBackground(Color.red);
					  jtb_24.setEnabled(false);
				  }
				  if(e.getSource()==jtb_25)
				  {
				     jtb_25.setText("B");
					  jtb_25.setBackground(Color.red);
					  jtb_25.setEnabled(false);
				  }
				  if(e.getSource()==jtb_26)
				  {
				     jtb_26.setText("B");
					  jtb_26.setBackground(Color.red);
					  jtb_26.setEnabled(false);
				  }
				  if(e.getSource()==jtb_27)
				  {
				     jtb_27.setText("B");
					  jtb_27.setBackground(Color.red);
					  jtb_27.setEnabled(false);
				  }
				  if(e.getSource()==jtb_28)
				  {
				     jtb_28.setText("B");
					  jtb_28.setBackground(Color.red);
					  jtb_28.setEnabled(false);
				  }
				  if(e.getSource()==jtb_29)
				  {
				     jtb_29.setText("B");
					  jtb_29.setBackground(Color.red);
					  jtb_29.setEnabled(false);
				  }
				  if(e.getSource()==jtb_30)
				  {
				     jtb_30.setText("B");
					  jtb_30.setBackground(Color.red);
					  jtb_30.setEnabled(false);
				  }
			  }
		  };
		  jtb_1.addActionListener(al);
		  jtb_2.addActionListener(al);
		  jtb_3.addActionListener(al);
		  jtb_4.addActionListener(al);
		  jtb_5.addActionListener(al);
		  jtb_6.addActionListener(al);
		  jtb_7.addActionListener(al);
		  jtb_8.addActionListener(al);
		  jtb_9.addActionListener(al);
		  jtb_10.addActionListener(al);
		  jtb_11.addActionListener(al);
		  jtb_12.addActionListener(al);
		  jtb_13.addActionListener(al);
		  jtb_14.addActionListener(al);
		  jtb_15.addActionListener(al);
		  jtb_16.addActionListener(al);
		  jtb_17.addActionListener(al);
		  jtb_18.addActionListener(al);
		  jtb_19.addActionListener(al);
		  jtb_20.addActionListener(al);
		  jtb_21.addActionListener(al);
		  jtb_22.addActionListener(al);
		  jtb_23.addActionListener(al);
		  jtb_24.addActionListener(al);
		  jtb_25.addActionListener(al);
		  jtb_26.addActionListener(al);
		  jtb_27.addActionListener(al);
		  jtb_28.addActionListener(al);
		  jtb_29.addActionListener(al);
		  jtb_30.addActionListener(al);
	 }	  

    public static void main (String[] args) {
       new Button();
    }
}
